"""
Django settings for ishisystemswebsite project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
 

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))   
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
 
STATIC_URL =  '/static/'
STATIC_ROOT = 'C:/virtualenv/ishisystemsenv/ishisystemswebsite/ishisystems/static/'
 

 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!2c(=z3ugc1*^gj@fc8vcmgxrx%s5b-=hzcnz6*h%5l3#zf%ng'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'grappelli',
    'django.contrib.admin.apps.SimpleAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',  
    'ishisystems',  
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
     
)

ROOT_URLCONF = 'ishisystemswebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', 
        'DIRS': [os.path.join(BASE_DIR, 'ishisystems/templates/ishisystems')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.contrib.auth.context_processors.auth",
                "django.core.context_processors.debug",
                "django.core.context_processors.i18n",
                "django.core.context_processors.media",
                "django.core.context_processors.static",
                "django.core.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
                "django.core.context_processors.request", 
                "ishisystemswebsite.context_processors.app_linkedin_url",
                "ishisystemswebsite.context_processors.app_twitter_url",
                "ishisystemswebsite.context_processors.app_blog_url",
                "ishisystemswebsite.context_processors.app_request_email_address",
                "ishisystemswebsite.context_processors.app_careers_email_address",
                "ishisystemswebsite.context_processors.app_directions_path_website",
                "ishisystemswebsite.context_processors.app_contactus_email_address",
                "ishisystemswebsite.context_processors.app_cloud_native_download_link",
                "ishisystemswebsite.context_processors.app_cloud_native_brochure_download_link",
				"ishisystemswebsite.context_processors.app_carousel_learn_more_link",
            ],
        },
    },
]

WSGI_APPLICATION = 'ishisystemswebsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ishi_systems',
        'USER':'admin',
        'PASSWORD':'pass123',
        'TEST': {
            'NAME': 'test_ishi_systems',
        },
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


#constants for IshiSystems.
APP_LINKEDIN_URL = 'https://www.linkedin.com/company/ishi-systems-inc.?trk=fc_badge'
APP_TWITTER_URL = 'http://www.twitter.com/ishisystems' 
APP_BLOG_URL = 'http://blog.ishisystems.com/'
APP_CAROUSEL_LEARN_MORE_LINK = 'http://blog.ishisystems.com/?p=53'
APP_REQUEST_EMAIL_ADDRESS = 'info@ishisystems.com'
APP_CAREERS_EMAIL_ADDRESS = 'careers@ishisystems.com'
APP_DIRECTIONS_PATH_WEBSITE = 'http://www.panynj.gov/'
#Change this email address for contactus email
APP_CONTACTUS_EMAIL_ADDRESS = 'pateljigyasa@gmail.com'
APP_CLOUD_NATIVE_WHITEPAPER_DOWNLOAD_LINK = 'http://cloudnative.ishisystems.com/whitepaper/download'
APP_CLOUD_NATIVE_BROCHURE_DOWNLOAD_LINK = "http://cloudnative.ishisystems.com/brochure/download/"

#For email
#Need to change email setting for sending emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
EMAIL_USE_TLS = True 
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_HOST_USER = 'pateljigyasa@gmail.com'  
EMAIL_HOST_PASSWORD = 'parvati@vishnu3' 
EMAIL_PORT = 587

"""Setting for customization of Grappelli admin tool"""
GRAPPELLI_ADMIN_TITLE ='Ishi Systems'
GRAPPELLI_CLEAN_INPUT_TYPES = True;
